trigger:
  paths:
    exclude:
      - README.md
      - LICENSE
      - .gitignore
      - azure-pipelines.yml
      - apply.yaml

resources:
  - repo: self
pool: "Azure Pipelines"

variables:
  image-repo: 'bupt2018/memes-fe'

stages:
  - stage: BuildAndPush
    displayName: BuildAndPush
    jobs:
      - job: BuildAndPush
        displayName: BuildAndPush

        steps:
          - task: CmdLine@2
            inputs:
              script: ' x=`echo "$(Build.SourceVersion)" | head -c 8`; echo "##vso[task.setvariable variable=SHORT_COMMIT]$x"'

          - task: Docker@2
            inputs:
              containerRegistry: 'ACR'
              repository: "$(image-repo)"
              command: 'buildAndPush'
              tags: '$(Build.BuildNumber)-$(SHORT_COMMIT)'
              Dockerfile: '**/Dockerfile'

#          - script: |
#              curl --location --request PUT --X PUT 'http://cd.bupt.site:30303/api/v1/deployments' --header 'Content-Type: application/json'  --header 'key: hello'  --header 'value: world'    --data '{ "namespace":"wanz","deployment":"cd-fe","container": "cd-fe","image": "registry.cn-beijing.aliyuncs.com/$(image-repo):$(Build.BuildNumber)-$(SHORT_COMMIT)"}'
#            displayName: 'send curl'
